name: Github Actions C++ Standard
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Before Install
        run: |
          pip install requests
          sudo apt-get install g++
      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EXPECTED_COVERAGE: ${{ secrets.EXPECTED_COVERAGE }}
        run: |
          g++ -std=c++11 -o TestBinary -fprofile-arcs -ftest-coverage test/test_index.cpp
          ./TestBinary
          gcov -o . test/test_index.cpp
      - name: Run tests and collect coverage
        run: pwd
      - name: Run tests and collect coverage
        run: ls -la
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          gcov-options: '\-lp'
          